/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type * as agentSkillsHttp from "../agentSkillsHttp.js";
import type * as appMeta from "../appMeta.js";
import type * as auth from "../auth.js";
import type * as canonicalTrending from "../canonicalTrending.js";
import type * as canonicalTrendingTestFixtures from "../canonicalTrendingTestFixtures.js";
import type * as catalogClassification from "../catalogClassification.js";
import type * as catalogClassificationNode from "../catalogClassificationNode.js";
import type * as catalogFeed from "../catalogFeed.js";
import type * as catalogTopics from "../catalogTopics.js";
import type * as cliDeviceAuth from "../cliDeviceAuth.js";
import type * as crons from "../crons.js";
import type * as dashboard from "../dashboard.js";
import type * as depRegistryScan from "../depRegistryScan.js";
import type * as devSeed from "../devSeed.js";
import type * as devSeedExtra from "../devSeedExtra.js";
import type * as downloadMetrics from "../downloadMetrics.js";
import type * as downloads from "../downloads.js";
import type * as emailsNode from "../emailsNode.js";
import type * as functions from "../functions.js";
import type * as githubAccountAgeBackfill from "../githubAccountAgeBackfill.js";
import type * as githubIdentity from "../githubIdentity.js";
import type * as githubImport from "../githubImport.js";
import type * as githubOrgMemberships from "../githubOrgMemberships.js";
import type * as githubSkillSources from "../githubSkillSources.js";
import type * as githubSkillSync from "../githubSkillSync.js";
import type * as githubSkillSyncNode from "../githubSkillSyncNode.js";
import type * as http from "../http.js";
import type * as httpApi from "../httpApi.js";
import type * as httpApiV1 from "../httpApiV1.js";
import type * as httpApiV1_catalogFeedV1 from "../httpApiV1/catalogFeedV1.js";
import type * as httpApiV1_contentRightsV1 from "../httpApiV1/contentRightsV1.js";
import type * as httpApiV1_docsSessionV1 from "../httpApiV1/docsSessionV1.js";
import type * as httpApiV1_packagePublishRecoveryV1 from "../httpApiV1/packagePublishRecoveryV1.js";
import type * as httpApiV1_packagesV1 from "../httpApiV1/packagesV1.js";
import type * as httpApiV1_promotionsV1 from "../httpApiV1/promotionsV1.js";
import type * as httpApiV1_publishersV1 from "../httpApiV1/publishersV1.js";
import type * as httpApiV1_shared from "../httpApiV1/shared.js";
import type * as httpApiV1_skillsShCatalogV1 from "../httpApiV1/skillsShCatalogV1.js";
import type * as httpApiV1_skillsV1 from "../httpApiV1/skillsV1.js";
import type * as httpApiV1_starsV1 from "../httpApiV1/starsV1.js";
import type * as httpApiV1_transfersV1 from "../httpApiV1/transfersV1.js";
import type * as httpApiV1_trendingV1 from "../httpApiV1/trendingV1.js";
import type * as httpApiV1_usersV1 from "../httpApiV1/usersV1.js";
import type * as httpApiV1_whoamiV1 from "../httpApiV1/whoamiV1.js";
import type * as httpPreflight from "../httpPreflight.js";
import type * as leaderboards from "../leaderboards.js";
import type * as lib_access from "../lib/access.js";
import type * as lib_agentSkillsDiscovery from "../lib/agentSkillsDiscovery.js";
import type * as lib_aigAnalysis from "../lib/aigAnalysis.js";
import type * as lib_apiTokenAuth from "../lib/apiTokenAuth.js";
import type * as lib_archiveManifest from "../lib/archiveManifest.js";
import type * as lib_artifactModeration from "../lib/artifactModeration.js";
import type * as lib_artifactText from "../lib/artifactText.js";
import type * as lib_badges from "../lib/badges.js";
import type * as lib_batching from "../lib/batching.js";
import type * as lib_canonicalSkillSearch from "../lib/canonicalSkillSearch.js";
import type * as lib_canonicalSkillSearchBounds from "../lib/canonicalSkillSearchBounds.js";
import type * as lib_canonicalSkillSearchResponse from "../lib/canonicalSkillSearchResponse.js";
import type * as lib_canonicalTrending from "../lib/canonicalTrending.js";
import type * as lib_canonicalTrendingPagination from "../lib/canonicalTrendingPagination.js";
import type * as lib_catalogClassification from "../lib/catalogClassification.js";
import type * as lib_catalogClassifier from "../lib/catalogClassifier.js";
import type * as lib_changelog from "../lib/changelog.js";
import type * as lib_clawhubVercelOidc from "../lib/clawhubVercelOidc.js";
import type * as lib_clawpack from "../lib/clawpack.js";
import type * as lib_contentTypes from "../lib/contentTypes.js";
import type * as lib_devAuth from "../lib/devAuth.js";
import type * as lib_devSeed from "../lib/devSeed.js";
import type * as lib_downloadTrend from "../lib/downloadTrend.js";
import type * as lib_emailRendering from "../lib/emailRendering.js";
import type * as lib_emails from "../lib/emails.js";
import type * as lib_embeddingVisibility from "../lib/embeddingVisibility.js";
import type * as lib_embeddings from "../lib/embeddings.js";
import type * as lib_experimentalClaws from "../lib/experimentalClaws.js";
import type * as lib_githubAccount from "../lib/githubAccount.js";
import type * as lib_githubActionsOidc from "../lib/githubActionsOidc.js";
import type * as lib_githubAuth from "../lib/githubAuth.js";
import type * as lib_githubHandoff from "../lib/githubHandoff.js";
import type * as lib_githubIdentity from "../lib/githubIdentity.js";
import type * as lib_githubImport from "../lib/githubImport.js";
import type * as lib_githubOrgMemberships from "../lib/githubOrgMemberships.js";
import type * as lib_githubProfileSync from "../lib/githubProfileSync.js";
import type * as lib_githubRepositoryDispatch from "../lib/githubRepositoryDispatch.js";
import type * as lib_githubSkillScans from "../lib/githubSkillScans.js";
import type * as lib_githubSkillSync from "../lib/githubSkillSync.js";
import type * as lib_globalStats from "../lib/globalStats.js";
import type * as lib_httpHeaders from "../lib/httpHeaders.js";
import type * as lib_httpPathSegments from "../lib/httpPathSegments.js";
import type * as lib_httpRateLimit from "../lib/httpRateLimit.js";
import type * as lib_httpRouteRateLimit from "../lib/httpRouteRateLimit.js";
import type * as lib_httpUtils from "../lib/httpUtils.js";
import type * as lib_installResolver from "../lib/installResolver.js";
import type * as lib_leaderboards from "../lib/leaderboards.js";
import type * as lib_moderation from "../lib/moderation.js";
import type * as lib_moderationEngine from "../lib/moderationEngine.js";
import type * as lib_moderationReasonCodes from "../lib/moderationReasonCodes.js";
import type * as lib_observabilityEvents from "../lib/observabilityEvents.js";
import type * as lib_officialPublishers from "../lib/officialPublishers.js";
import type * as lib_openClawPublishAuthorization from "../lib/openClawPublishAuthorization.js";
import type * as lib_openaiResponse from "../lib/openaiResponse.js";
import type * as lib_packageArtifacts from "../lib/packageArtifacts.js";
import type * as lib_packagePublishRecovery from "../lib/packagePublishRecovery.js";
import type * as lib_packageRegistry from "../lib/packageRegistry.js";
import type * as lib_packageRuntimeIdentity from "../lib/packageRuntimeIdentity.js";
import type * as lib_packageSearchDigest from "../lib/packageSearchDigest.js";
import type * as lib_packageSecurity from "../lib/packageSecurity.js";
import type * as lib_packageStatEvents from "../lib/packageStatEvents.js";
import type * as lib_public from "../lib/public.js";
import type * as lib_publicBrowse from "../lib/publicBrowse.js";
import type * as lib_publicRouteReservations from "../lib/publicRouteReservations.js";
import type * as lib_publishLimits from "../lib/publishLimits.js";
import type * as lib_publisherAbuseOwnerSynchrony from "../lib/publisherAbuseOwnerSynchrony.js";
import type * as lib_publisherAbuseScoring from "../lib/publisherAbuseScoring.js";
import type * as lib_publisherCatalogDisplay from "../lib/publisherCatalogDisplay.js";
import type * as lib_publisherStats from "../lib/publisherStats.js";
import type * as lib_publishers from "../lib/publishers.js";
import type * as lib_rankingMetricsImportLock from "../lib/rankingMetricsImportLock.js";
import type * as lib_recommendationScore from "../lib/recommendationScore.js";
import type * as lib_reporting from "../lib/reporting.js";
import type * as lib_reservedHandles from "../lib/reservedHandles.js";
import type * as lib_reservedSlugs from "../lib/reservedSlugs.js";
import type * as lib_retentionPolicy from "../lib/retentionPolicy.js";
import type * as lib_rolloutCapabilities from "../lib/rolloutCapabilities.js";
import type * as lib_searchRanking from "../lib/searchRanking.js";
import type * as lib_searchText from "../lib/searchText.js";
import type * as lib_securityPrompt from "../lib/securityPrompt.js";
import type * as lib_securityScanPolicy from "../lib/securityScanPolicy.js";
import type * as lib_skillBackfill from "../lib/skillBackfill.js";
import type * as lib_skillCards from "../lib/skillCards.js";
import type * as lib_skillDownloadBackfill from "../lib/skillDownloadBackfill.js";
import type * as lib_skillEvaluationConfig from "../lib/skillEvaluationConfig.js";
import type * as lib_skillEvaluationResult from "../lib/skillEvaluationResult.js";
import type * as lib_skillFileAccess from "../lib/skillFileAccess.js";
import type * as lib_skillHourlyStats from "../lib/skillHourlyStats.js";
import type * as lib_skillInstallBackfill from "../lib/skillInstallBackfill.js";
import type * as lib_skillPresentation from "../lib/skillPresentation.js";
import type * as lib_skillPresentationBackfill from "../lib/skillPresentationBackfill.js";
import type * as lib_skillPublish from "../lib/skillPublish.js";
import type * as lib_skillQuality from "../lib/skillQuality.js";
import type * as lib_skillSafety from "../lib/skillSafety.js";
import type * as lib_skillScanRequestFiles from "../lib/skillScanRequestFiles.js";
import type * as lib_skillSearchDigest from "../lib/skillSearchDigest.js";
import type * as lib_skillSlugValidator from "../lib/skillSlugValidator.js";
import type * as lib_skillStats from "../lib/skillStats.js";
import type * as lib_skillSummary from "../lib/skillSummary.js";
import type * as lib_skillTags from "../lib/skillTags.js";
import type * as lib_skillZip from "../lib/skillZip.js";
import type * as lib_skills_index from "../lib/skills/index.js";
import type * as lib_skills_slugResolution from "../lib/skills/slugResolution.js";
import type * as lib_skillsShCatalogEnvironment from "../lib/skillsShCatalogEnvironment.js";
import type * as lib_skillsShCatalogFixtures from "../lib/skillsShCatalogFixtures.js";
import type * as lib_skillsShCatalogPublication from "../lib/skillsShCatalogPublication.js";
import type * as lib_skillsShMirrorPublic from "../lib/skillsShMirrorPublic.js";
import type * as lib_skillsShPublicVisibility from "../lib/skillsShPublicVisibility.js";
import type * as lib_staticPublishScan from "../lib/staticPublishScan.js";
import type * as lib_storageDigests from "../lib/storageDigests.js";
import type * as lib_testSeed from "../lib/testSeed.js";
import type * as lib_tokens from "../lib/tokens.js";
import type * as lib_userSearch from "../lib/userSearch.js";
import type * as lib_userSkillStats from "../lib/userSkillStats.js";
import type * as lib_webhooks from "../lib/webhooks.js";
import type * as lib_workerTextRedaction from "../lib/workerTextRedaction.js";
import type * as maintenance from "../maintenance.js";
import type * as managementDevSeed from "../managementDevSeed.js";
import type * as migrations from "../migrations.js";
import type * as packageInspectorHttp from "../packageInspectorHttp.js";
import type * as packageInspectorNode from "../packageInspectorNode.js";
import type * as packageLeaderboards from "../packageLeaderboards.js";
import type * as packagePublishRecovery from "../packagePublishRecovery.js";
import type * as packagePublishTokens from "../packagePublishTokens.js";
import type * as packages from "../packages.js";
import type * as prepublicationObservability from "../prepublicationObservability.js";
import type * as promotions from "../promotions.js";
import type * as promotionsFeed from "../promotionsFeed.js";
import type * as publishAttemptDispatch from "../publishAttemptDispatch.js";
import type * as publishAttempts from "../publishAttempts.js";
import type * as publisherAbuse from "../publisherAbuse.js";
import type * as publisherAbuseDevSeed from "../publisherAbuseDevSeed.js";
import type * as publisherAbuseOwnerSynchrony from "../publisherAbuseOwnerSynchrony.js";
import type * as publisherAbuseTemporalScan from "../publisherAbuseTemporalScan.js";
import type * as publishers from "../publishers.js";
import type * as rateLimits from "../rateLimits.js";
import type * as retention from "../retention.js";
import type * as rolloutCapabilities from "../rolloutCapabilities.js";
import type * as search from "../search.js";
import type * as searchTestFixtures from "../searchTestFixtures.js";
import type * as securityDataset from "../securityDataset.js";
import type * as securityDatasetNode from "../securityDatasetNode.js";
import type * as securityScan from "../securityScan.js";
import type * as securityScanDispatch from "../securityScanDispatch.js";
import type * as skillCards from "../skillCards.js";
import type * as skillEvaluationDispatch from "../skillEvaluationDispatch.js";
import type * as skillEvaluations from "../skillEvaluations.js";
import type * as skillHourlyStats from "../skillHourlyStats.js";
import type * as skillPresentationAssets from "../skillPresentationAssets.js";
import type * as skillPresentationAssetsHttp from "../skillPresentationAssetsHttp.js";
import type * as skillPresentationBackfill from "../skillPresentationBackfill.js";
import type * as skillPresentationImageNode from "../skillPresentationImageNode.js";
import type * as skillPublishUploads from "../skillPublishUploads.js";
import type * as skillStatEvents from "../skillStatEvents.js";
import type * as skillTransfers from "../skillTransfers.js";
import type * as skills from "../skills.js";
import type * as skillsShCatalog from "../skillsShCatalog.js";
import type * as skillsShClaims from "../skillsShClaims.js";
import type * as skillsShMirror from "../skillsShMirror.js";
import type * as skillsShMirrorPublic from "../skillsShMirrorPublic.js";
import type * as skillsShMirrorVisibility from "../skillsShMirrorVisibility.js";
import type * as skillsShPublicTestFixtures from "../skillsShPublicTestFixtures.js";
import type * as stars from "../stars.js";
import type * as staticPublishScanNode from "../staticPublishScanNode.js";
import type * as statsMaintenance from "../statsMaintenance.js";
import type * as telemetry from "../telemetry.js";
import type * as tokens from "../tokens.js";
import type * as uploads from "../uploads.js";
import type * as users from "../users.js";
import type * as vt from "../vt.js";
import type * as webhooks from "../webhooks.js";

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

declare const fullApi: ApiFromModules<{
  agentSkillsHttp: typeof agentSkillsHttp;
  appMeta: typeof appMeta;
  auth: typeof auth;
  canonicalTrending: typeof canonicalTrending;
  canonicalTrendingTestFixtures: typeof canonicalTrendingTestFixtures;
  catalogClassification: typeof catalogClassification;
  catalogClassificationNode: typeof catalogClassificationNode;
  catalogFeed: typeof catalogFeed;
  catalogTopics: typeof catalogTopics;
  cliDeviceAuth: typeof cliDeviceAuth;
  crons: typeof crons;
  dashboard: typeof dashboard;
  depRegistryScan: typeof depRegistryScan;
  devSeed: typeof devSeed;
  devSeedExtra: typeof devSeedExtra;
  downloadMetrics: typeof downloadMetrics;
  downloads: typeof downloads;
  emailsNode: typeof emailsNode;
  functions: typeof functions;
  githubAccountAgeBackfill: typeof githubAccountAgeBackfill;
  githubIdentity: typeof githubIdentity;
  githubImport: typeof githubImport;
  githubOrgMemberships: typeof githubOrgMemberships;
  githubSkillSources: typeof githubSkillSources;
  githubSkillSync: typeof githubSkillSync;
  githubSkillSyncNode: typeof githubSkillSyncNode;
  http: typeof http;
  httpApi: typeof httpApi;
  httpApiV1: typeof httpApiV1;
  "httpApiV1/catalogFeedV1": typeof httpApiV1_catalogFeedV1;
  "httpApiV1/contentRightsV1": typeof httpApiV1_contentRightsV1;
  "httpApiV1/docsSessionV1": typeof httpApiV1_docsSessionV1;
  "httpApiV1/packagePublishRecoveryV1": typeof httpApiV1_packagePublishRecoveryV1;
  "httpApiV1/packagesV1": typeof httpApiV1_packagesV1;
  "httpApiV1/promotionsV1": typeof httpApiV1_promotionsV1;
  "httpApiV1/publishersV1": typeof httpApiV1_publishersV1;
  "httpApiV1/shared": typeof httpApiV1_shared;
  "httpApiV1/skillsShCatalogV1": typeof httpApiV1_skillsShCatalogV1;
  "httpApiV1/skillsV1": typeof httpApiV1_skillsV1;
  "httpApiV1/starsV1": typeof httpApiV1_starsV1;
  "httpApiV1/transfersV1": typeof httpApiV1_transfersV1;
  "httpApiV1/trendingV1": typeof httpApiV1_trendingV1;
  "httpApiV1/usersV1": typeof httpApiV1_usersV1;
  "httpApiV1/whoamiV1": typeof httpApiV1_whoamiV1;
  httpPreflight: typeof httpPreflight;
  leaderboards: typeof leaderboards;
  "lib/access": typeof lib_access;
  "lib/agentSkillsDiscovery": typeof lib_agentSkillsDiscovery;
  "lib/aigAnalysis": typeof lib_aigAnalysis;
  "lib/apiTokenAuth": typeof lib_apiTokenAuth;
  "lib/archiveManifest": typeof lib_archiveManifest;
  "lib/artifactModeration": typeof lib_artifactModeration;
  "lib/artifactText": typeof lib_artifactText;
  "lib/badges": typeof lib_badges;
  "lib/batching": typeof lib_batching;
  "lib/canonicalSkillSearch": typeof lib_canonicalSkillSearch;
  "lib/canonicalSkillSearchBounds": typeof lib_canonicalSkillSearchBounds;
  "lib/canonicalSkillSearchResponse": typeof lib_canonicalSkillSearchResponse;
  "lib/canonicalTrending": typeof lib_canonicalTrending;
  "lib/canonicalTrendingPagination": typeof lib_canonicalTrendingPagination;
  "lib/catalogClassification": typeof lib_catalogClassification;
  "lib/catalogClassifier": typeof lib_catalogClassifier;
  "lib/changelog": typeof lib_changelog;
  "lib/clawhubVercelOidc": typeof lib_clawhubVercelOidc;
  "lib/clawpack": typeof lib_clawpack;
  "lib/contentTypes": typeof lib_contentTypes;
  "lib/devAuth": typeof lib_devAuth;
  "lib/devSeed": typeof lib_devSeed;
  "lib/downloadTrend": typeof lib_downloadTrend;
  "lib/emailRendering": typeof lib_emailRendering;
  "lib/emails": typeof lib_emails;
  "lib/embeddingVisibility": typeof lib_embeddingVisibility;
  "lib/embeddings": typeof lib_embeddings;
  "lib/experimentalClaws": typeof lib_experimentalClaws;
  "lib/githubAccount": typeof lib_githubAccount;
  "lib/githubActionsOidc": typeof lib_githubActionsOidc;
  "lib/githubAuth": typeof lib_githubAuth;
  "lib/githubHandoff": typeof lib_githubHandoff;
  "lib/githubIdentity": typeof lib_githubIdentity;
  "lib/githubImport": typeof lib_githubImport;
  "lib/githubOrgMemberships": typeof lib_githubOrgMemberships;
  "lib/githubProfileSync": typeof lib_githubProfileSync;
  "lib/githubRepositoryDispatch": typeof lib_githubRepositoryDispatch;
  "lib/githubSkillScans": typeof lib_githubSkillScans;
  "lib/githubSkillSync": typeof lib_githubSkillSync;
  "lib/globalStats": typeof lib_globalStats;
  "lib/httpHeaders": typeof lib_httpHeaders;
  "lib/httpPathSegments": typeof lib_httpPathSegments;
  "lib/httpRateLimit": typeof lib_httpRateLimit;
  "lib/httpRouteRateLimit": typeof lib_httpRouteRateLimit;
  "lib/httpUtils": typeof lib_httpUtils;
  "lib/installResolver": typeof lib_installResolver;
  "lib/leaderboards": typeof lib_leaderboards;
  "lib/moderation": typeof lib_moderation;
  "lib/moderationEngine": typeof lib_moderationEngine;
  "lib/moderationReasonCodes": typeof lib_moderationReasonCodes;
  "lib/observabilityEvents": typeof lib_observabilityEvents;
  "lib/officialPublishers": typeof lib_officialPublishers;
  "lib/openClawPublishAuthorization": typeof lib_openClawPublishAuthorization;
  "lib/openaiResponse": typeof lib_openaiResponse;
  "lib/packageArtifacts": typeof lib_packageArtifacts;
  "lib/packagePublishRecovery": typeof lib_packagePublishRecovery;
  "lib/packageRegistry": typeof lib_packageRegistry;
  "lib/packageRuntimeIdentity": typeof lib_packageRuntimeIdentity;
  "lib/packageSearchDigest": typeof lib_packageSearchDigest;
  "lib/packageSecurity": typeof lib_packageSecurity;
  "lib/packageStatEvents": typeof lib_packageStatEvents;
  "lib/public": typeof lib_public;
  "lib/publicBrowse": typeof lib_publicBrowse;
  "lib/publicRouteReservations": typeof lib_publicRouteReservations;
  "lib/publishLimits": typeof lib_publishLimits;
  "lib/publisherAbuseOwnerSynchrony": typeof lib_publisherAbuseOwnerSynchrony;
  "lib/publisherAbuseScoring": typeof lib_publisherAbuseScoring;
  "lib/publisherCatalogDisplay": typeof lib_publisherCatalogDisplay;
  "lib/publisherStats": typeof lib_publisherStats;
  "lib/publishers": typeof lib_publishers;
  "lib/rankingMetricsImportLock": typeof lib_rankingMetricsImportLock;
  "lib/recommendationScore": typeof lib_recommendationScore;
  "lib/reporting": typeof lib_reporting;
  "lib/reservedHandles": typeof lib_reservedHandles;
  "lib/reservedSlugs": typeof lib_reservedSlugs;
  "lib/retentionPolicy": typeof lib_retentionPolicy;
  "lib/rolloutCapabilities": typeof lib_rolloutCapabilities;
  "lib/searchRanking": typeof lib_searchRanking;
  "lib/searchText": typeof lib_searchText;
  "lib/securityPrompt": typeof lib_securityPrompt;
  "lib/securityScanPolicy": typeof lib_securityScanPolicy;
  "lib/skillBackfill": typeof lib_skillBackfill;
  "lib/skillCards": typeof lib_skillCards;
  "lib/skillDownloadBackfill": typeof lib_skillDownloadBackfill;
  "lib/skillEvaluationConfig": typeof lib_skillEvaluationConfig;
  "lib/skillEvaluationResult": typeof lib_skillEvaluationResult;
  "lib/skillFileAccess": typeof lib_skillFileAccess;
  "lib/skillHourlyStats": typeof lib_skillHourlyStats;
  "lib/skillInstallBackfill": typeof lib_skillInstallBackfill;
  "lib/skillPresentation": typeof lib_skillPresentation;
  "lib/skillPresentationBackfill": typeof lib_skillPresentationBackfill;
  "lib/skillPublish": typeof lib_skillPublish;
  "lib/skillQuality": typeof lib_skillQuality;
  "lib/skillSafety": typeof lib_skillSafety;
  "lib/skillScanRequestFiles": typeof lib_skillScanRequestFiles;
  "lib/skillSearchDigest": typeof lib_skillSearchDigest;
  "lib/skillSlugValidator": typeof lib_skillSlugValidator;
  "lib/skillStats": typeof lib_skillStats;
  "lib/skillSummary": typeof lib_skillSummary;
  "lib/skillTags": typeof lib_skillTags;
  "lib/skillZip": typeof lib_skillZip;
  "lib/skills/index": typeof lib_skills_index;
  "lib/skills/slugResolution": typeof lib_skills_slugResolution;
  "lib/skillsShCatalogEnvironment": typeof lib_skillsShCatalogEnvironment;
  "lib/skillsShCatalogFixtures": typeof lib_skillsShCatalogFixtures;
  "lib/skillsShCatalogPublication": typeof lib_skillsShCatalogPublication;
  "lib/skillsShMirrorPublic": typeof lib_skillsShMirrorPublic;
  "lib/skillsShPublicVisibility": typeof lib_skillsShPublicVisibility;
  "lib/staticPublishScan": typeof lib_staticPublishScan;
  "lib/storageDigests": typeof lib_storageDigests;
  "lib/testSeed": typeof lib_testSeed;
  "lib/tokens": typeof lib_tokens;
  "lib/userSearch": typeof lib_userSearch;
  "lib/userSkillStats": typeof lib_userSkillStats;
  "lib/webhooks": typeof lib_webhooks;
  "lib/workerTextRedaction": typeof lib_workerTextRedaction;
  maintenance: typeof maintenance;
  managementDevSeed: typeof managementDevSeed;
  migrations: typeof migrations;
  packageInspectorHttp: typeof packageInspectorHttp;
  packageInspectorNode: typeof packageInspectorNode;
  packageLeaderboards: typeof packageLeaderboards;
  packagePublishRecovery: typeof packagePublishRecovery;
  packagePublishTokens: typeof packagePublishTokens;
  packages: typeof packages;
  prepublicationObservability: typeof prepublicationObservability;
  promotions: typeof promotions;
  promotionsFeed: typeof promotionsFeed;
  publishAttemptDispatch: typeof publishAttemptDispatch;
  publishAttempts: typeof publishAttempts;
  publisherAbuse: typeof publisherAbuse;
  publisherAbuseDevSeed: typeof publisherAbuseDevSeed;
  publisherAbuseOwnerSynchrony: typeof publisherAbuseOwnerSynchrony;
  publisherAbuseTemporalScan: typeof publisherAbuseTemporalScan;
  publishers: typeof publishers;
  rateLimits: typeof rateLimits;
  retention: typeof retention;
  rolloutCapabilities: typeof rolloutCapabilities;
  search: typeof search;
  searchTestFixtures: typeof searchTestFixtures;
  securityDataset: typeof securityDataset;
  securityDatasetNode: typeof securityDatasetNode;
  securityScan: typeof securityScan;
  securityScanDispatch: typeof securityScanDispatch;
  skillCards: typeof skillCards;
  skillEvaluationDispatch: typeof skillEvaluationDispatch;
  skillEvaluations: typeof skillEvaluations;
  skillHourlyStats: typeof skillHourlyStats;
  skillPresentationAssets: typeof skillPresentationAssets;
  skillPresentationAssetsHttp: typeof skillPresentationAssetsHttp;
  skillPresentationBackfill: typeof skillPresentationBackfill;
  skillPresentationImageNode: typeof skillPresentationImageNode;
  skillPublishUploads: typeof skillPublishUploads;
  skillStatEvents: typeof skillStatEvents;
  skillTransfers: typeof skillTransfers;
  skills: typeof skills;
  skillsShCatalog: typeof skillsShCatalog;
  skillsShClaims: typeof skillsShClaims;
  skillsShMirror: typeof skillsShMirror;
  skillsShMirrorPublic: typeof skillsShMirrorPublic;
  skillsShMirrorVisibility: typeof skillsShMirrorVisibility;
  skillsShPublicTestFixtures: typeof skillsShPublicTestFixtures;
  stars: typeof stars;
  staticPublishScanNode: typeof staticPublishScanNode;
  statsMaintenance: typeof statsMaintenance;
  telemetry: typeof telemetry;
  tokens: typeof tokens;
  uploads: typeof uploads;
  users: typeof users;
  vt: typeof vt;
  webhooks: typeof webhooks;
}>;

/**
 * A utility for referencing Convex functions in your app's public API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;

/**
 * A utility for referencing Convex functions in your app's internal API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = internal.myModule.myFunction;
 * ```
 */
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;

export declare const components: {
  migrations: import("@convex-dev/migrations/_generated/component.js").ComponentApi<"migrations">;
  rateLimiter: import("@convex-dev/rate-limiter/_generated/component.js").ComponentApi<"rateLimiter">;
};
